config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :locations, only: [:index, :create, :update] do
      get :random, on: :collection
      post :notifications, on: :member
    end
    resources :moderation_notifications, path: '/notifications', only: [:create]
    resources :reviews, only: [:index, :create]
    resources :users, only: [:update]
    resources :teams, only: [:update]
    resources :events, only: [:create]
  end

  namespace :admin do
    resources :feature_settings, only: [:index, :update]
    resources :directory_segments, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:new, :create]
    resources :locations, only: [:index, :show] do
      post :fetch, on: :member

      get :pending, on: :collection
      get :rejected, on: :collection
      get :moderate, on: :collection
    end
    resources :users do
      get :edit_merge, on: :member
      post :merge, on: :member
    end
    resources :templates, only: [:show]
    root 'admin#index'
  end

  resources :users, :path => '/people', :only => [:index, :show, :create, :update, :destroy] do
    post :remove_image, on: :member
    resources :users, controller: :students, as: :students, path: '/students', only: [:create, :destroy, :index]
    resources :events, controller: :user_events, only: [:index]
    resources :reviews, controller: :user_reviews, only: [:index]
  end

  resources :articles, only: [:index, :show] do
    put :publish, on: :member
    put :unpublish, on: :member
  end

  resource :map, only: [:show] do
    get :search, on: :collection
  end

  resource :geocoder, only: [:show]
  resource :search, only: [:show], controller: :search

  resources :moderation_notifications, path: '/notifications', only: [:index] do
    put :dismiss, on: :member
  end
  resources :locations, only: [:create, :destroy, :update, :show] do
    post :favorite, on: :member
    get :wizard, on: :collection
    get :recent, on: :collection
    get :nearby, on: :collection
    get :random, on: :collection
    get :schedule, on: :member

    post :move, on: :member
    post :unlock, on: :member
    post :close, on: :member
    post :remove_image, on: :member

    resource :status, controller: :location_statuses, only: [] do
      put :verify, on: :member
      put :reject, on: :member
      put :pending, on: :member
    end

    resources :reviews, controller: :location_reviews, only: [:create, :destroy, :index]

    resources :users, controller: :instructors, as: :instructors, path: '/instructors', only: [:create, :destroy, :index]

    resources :events, controller: :location_events, only: [:create, :index, :show, :destroy, :update] do
      post :move, on: :member
    end
  end

  resources :verifications, controller: :location_owner_verifications, as: :verifications, path: '/verifications', only: [:create] do
    get :verify, on: :member
  end

  resources :teams, :only => [:show, :index, :update, :create, :new, :destroy] do
    post :remove_image, on: :member
    resources :users, controller: :instructors, as: :instructors, path: '/instructors', only: [:create, :destroy, :index]
  end

  resources :events, :only => [:index, :create] do
    get :wizard, on: :collection
    get :upcoming, on: :collection
  end

  root 'application#homepage'
  get '/bjj-academy-directory' => 'directory_segments#index', :as => :directory_index
  get '/bjj-academy-directory/country/:country(/city/:city)' => 'directory_segments#show', :as => :directory_segment

  match '/signin' => 'sessions#new', :as => :signin, :via => [:post, :get]
  match '/auth/:provider/callback' => 'sessions#create', :via => [:post, :get]
  match '/auth/failure' => 'sessions#failure', :via => [:post, :get]
  match '/signout' => 'sessions#destroy', :as => :signout, :via => [:post, :get, :delete]

  post '/report' => 'application#report', :as => :report
  get '/meta' => 'application#meta', :as => :meta
  get '/privacy-policy' => 'application#privacy_policy', :as => :privacy_policy
  get '/people' => 'application#people'
  post '/contact' => 'application#contact', :as => :contact

  get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
  def show
    location_id = params.fetch(:id, '')
    @location = Location.find(location_id)
  end

  def fetch
    location_id = params.fetch(:id, '')
    @location = Location.find(location_id)
    @location.search_metadata!
    head :no_content
  end

  def listings
    location_id = params.fetch(:id, '')
    @location = Location.find(location_id)
    scope = params.fetch(:scope, nil)
    @response = RollFindr::LocationFetchService.listings(location_id, scope: scope, lat: @location.lat, lng: @location.lng)
  end

  def associate
    location_id = params.fetch(:id, '')
    scope = params.fetch(:scope, nil)
    remote_id = params.fetch(:remote_id, nil)

    opts = { scope: scope }
    opts["#{scope.downcase}_id".to_sym] = remote_id
    RollFindr::LocationFetchService.associate(location_id, opts)

    head :no_content
  end

  def index
    @locations = Location.limit(100).sort({created_at:-1})
  end

  def pending
    order = params.fetch(:order, 1).to_i
    count = params.fetch(:count, 100).to_i
    offset = params.fetch(:offset, 0).to_i

    @locations = Location.limit(count).offset(offset).pending.sort({status_updated_at: order})
  end

  def rejected
    order = params.fetch(:order, 1).to_i
    count = params.fetch(:count, 100).to_i
    offset = params.fetch(:offset, 0).to_i
    
    @locations = Location.limit(count).offset(offset).rejected.sort({created_at: order})
  end

  def moderate
    order = params.fetch(:order, 1).to_i
    redirect_to location_path(Location.pending.sort({status_updated_at: order}).first, moderate: 1)
  end
end

app/controllers/api/locations_controller.rb
class Api::LocationsController < Api::ApiController
  include Api::LocationCreateParams
  include ModerationNotificationCreateParams

  DEFAULT_SEARCH_DISTANCE = 10.0
  DEFAULT_SEARCH_COUNT = 100

  before_filter :set_coordinates, only: [:index]
  before_filter :set_locations_scope, only: [:index]
  before_filter :filter_locations, only: [:index]

  helper_method :location

  def index
    respond_to do |format|
      format.json
    end
  end

  def create
    @location = Location.new(api_location_create_params)
    if @location.academy? && @location.team.nil?
      @location.team = guess_team(api_location_create_params[:title])
    end
    @location.save!
    
    ModerationNotification.create(type: ModerationNotification::TYPE_REVIEW_LOCATION,
                                  coordinates: @location.coordinates,
                                  message: "#{@location.title} was automatically created and requires review",
                                  source: "#{current_user.name} via Api::LocationsController", 
                                  info: { location_id: @location.id.to_s })

    respond_to do |format|
      format.json { render partial: 'locations/location' }
    end
  end

  def update
    id_param = params.fetch(:id, '')
    @location = Location.find(id_param)

    head :not_found and return false unless @location.present?

    @location.update!(api_location_create_params)

    respond_to do |format|
      format.json { render partial: 'locations/location' }
    end
  end

  def random
    scope = Location.academies.verified
    @location = scope.skip(rand(scope.count)).first

    respond_to do |format|
      format.json { render partial: 'locations/location' }
    end
  end

  private

  def location
    @location
  end

  def guess_team(title)
     Team.all.select{|t| title.downcase.index(t.name.downcase) != nil}.first
  end

  def flags
    Map::DEFAULT_FLAGS.keys.inject({}) do |hash, k|
      hash[k] = flag?(k) ? 1 : 0
      hash
    end
  end

  def flag?(f)
    params.fetch(f, 0).try(:to_i) == 1
  end

  def set_coordinates
    @geocode_query = params.fetch(:geoquery, nil)
    if @geocode_query.present?
      results = GeocodersHelper.search(@geocode_query)
      @lat = results.first.try(:lat)
      @lng = results.first.try(:lng)
    else
      @lat = params.fetch(:lat, nil).try(:to_f)
      @lng = params.fetch(:lng, nil).try(:to_f)
    end

    head :bad_request and return false unless @lat.present? && @lng.present?
  end

  def set_locations_scope
    @count = params.fetch(:count, DEFAULT_SEARCH_COUNT).to_i
    @offset = params.fetch(:offset, 0).to_i
    @text_filter = params.fetch(:query, nil)
    @distance = params.fetch(:distance, DEFAULT_SEARCH_DISTANCE).to_f

    return unless @lat.present? && @lng.present?
    @locations = Location
      .limit(@count)
      .offset(@offset)
      .where(:coordinates => { "$geoWithin" => { "$centerSphere" => [[@lng, @lat], @distance/3963.2] }})

    @locations = @locations.not_closed unless flag?(:closed)
    @locations = @locations.not_rejected unless flag?(:rejected)
    @locations = @locations.verified unless flag?(:unverified)
    @locations = @locations.with_black_belt if flag?(:bbonly)
    @locations = @locations.sort_by {|loc| Geocoder::Calculations.distance_between([@lat, @lng], loc.to_coordinates) }
    @locations
  end

  def filter_locations
    if @text_filter.present? && @locations.present?
      @locations = @locations.search(@text_filter)
    end

    @team = params.fetch(:team, [])
    @locations = @locations.where(:team_id.in => @team) if @team.present?
  end

  def set_timezone(&block)
    tz = RollFindr::TimezoneService.timezone_for(@lat, @lng) rescue nil
    Time.use_zone(tz, &block)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def format_address addr
    addr.split(',',2).join(tag(:br)).html_safe
  end

  def upload_image_location_path(location)
    "/service/avatar/upload/locations/#{location.id}/async"
  end

  def country_name_for(country)
    return '' unless country.present?
    return RollFindr::DirectoryCountryAbbreviations[country] || country
  end
end

app/views/admin/locations/_table.html.haml
%table.table.table-striped
  %tr
    %th Title
    %th Modifier
    %th Metadata
    %th Actions

  - @locations.each do |loc|
    %tr
      %td
        = link_to(loc.title, loc)
        = link_to('(admin)', admin_location_path(loc))
      %td
        = link_to(loc.modifier.try(:name), loc.modifier)
        .small= time_ago_in_words(loc.created_at)
      %td
        = JSON.pretty_generate(JSON.parse(render_json(loc)))
      %td.actions
        = link_to 'Verify!', verify_location_status_path(loc), :class => 'text-success', :'data-remote' => true, :'data-method' => 'PUT'
        = link_to 'Reject!', reject_location_status_path(loc), :class => 'text-danger', :'data-remote' => true, :'data-method' => 'PUT'
        = link_to 'Pending!', pending_location_status_path(loc), :class => 'text-warning', :'data-remote' => true, :'data-method' => 'PUT'
        = link_to 'Edit', location_path(loc, edit: 1)

= content_for(:scripts) do
  :javascript
    $(document).ready(function() {
      $('html').delegate('.actions a', 'click', function(e) {
        var cls = $(e.currentTarget).prop('class');
        $(e.currentTarget).parents('tr').addClass(cls);
      })
    });

app/views/admin/locations/index.html.haml
.container
  %h3 Last 50 Locations
  %table.table.table-striped
    %tr
      %th
      %th Modifier
      %th Metadata
      %th Time

    - @locations.each do |loc|
      %tr
        %td
          = link_to(loc.title, loc)
          = link_to('(admin)', meta_admin_location_path(loc))
        %td
          = link_to(loc.modifier.try(:name), loc.modifier)
        %td
          = JSON.pretty_generate(loc.as_json({}))
        %td= time_ago_in_words(loc.created_at)

app/views/admin/locations/meta.html.haml
.container
  %h3 Model
  %pre.small= JSON.pretty_generate(@location.as_json({}))
  %h3= pluralize(@location.history_tracks.count, "Changes")
  %table.table.table-striped
    %tr
      %th Action
      %th Modified
      %th Original
      %th Version
      %th Modifier
      %th Time

    - @location.history_tracks.sort_by { |o| -o.version }.each do |history|
      %tr
        %td= history.action
        %td
          %pre= JSON.pretty_generate(history.modified)
        %td
          %pre= JSON.pretty_generate(history.original)
        %td= history.version
        %td= history.modifier.present? ? link_to(history.modifier.name, history.modifier) : '(none)'
        %td= time_ago_in_words(history.created_at)

app/views/admin/locations/pending.html.haml
.container
  %h3 Last 100 Pending Locations
  = render partial: 'table', locals: { locations: @locations }

app/views/admin/locations/rejected.html.haml
.container
  %h3 Last 100 Pending Locations
  = render partial: 'table', locals: { locations: @locations }

app/views/admin/locations/show.html.haml
.container
  %h2
    = link_to location_path(@location, edit: 0) do
      = @location.title
    %span.small
      = surround '(', ')'  do
        = link_to 'Edit', location_path(@location, edit: 1)

  %h3 Actions
  = link_to 'Fetch!', fetch_admin_location_path(@location), :class => 'btn btn-primary', :'data-remote' => true, :'data-method' => 'POST'
  = link_to 'Verify!', verify_location_status_path(@location), :class => 'btn btn-success text-success', :'data-remote' => true, :'data-method' => 'PUT'
  = link_to 'Reject!', reject_location_status_path(@location), :class => 'btn btn-danger text-danger', :'data-remote' => true, :'data-method' => 'PUT'
  = link_to 'Pending!', pending_location_status_path(@location), :class => 'btn btn-warning text-warning', :'data-remote' => true, :'data-method' => 'PUT'

  = link_to 'Unlock!', unlock_location_path(@location), :class => 'btn btn-default', :'data-remote' => true, :'data-method' => 'POST'
  = link_to 'Close!', close_location_path(@location), :class => 'btn btn-default text-default', :'data-remote' => true, :'data-method' => 'POST'
  = link_to 'Delete!', location_path(@location), :class => 'btn btn-default text-default', :'data-remote' => true, :'data-method' => 'DELETE'
  %h3 Model
  %pre.small= JSON.pretty_generate(JSON.parse(render_json(@location)))
  %h3 Service Metadata
  %pre= JSON.pretty_generate(RollFindr::LocationFetchService.listings(@location.id.to_s, @location.address_components.merge(title: @location.title)) || {})
  
  %h3= pluralize(@location.history_tracks.count, "Changes")
  %table.table.table-striped
    %tr
      %th Action
      %th Modified
      %th Original
      %th Version
      %th Modifier
      %th Time

    - @location.history_tracks.sort_by { |o| -o.version }.each do |history|
      %tr
        %td= history.action
        %td
          %pre= JSON.pretty_generate(history.modified)
        %td
          %pre= JSON.pretty_generate(history.original)
        %td= history.version
        %td= history.modifier.present? ? link_to(history.modifier.name, history.modifier) : '(none)'
        %td= time_ago_in_words(history.created_at)