config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :locations, only: [:index, :create, :update] do
      get :random, on: :collection
      post :notifications, on: :member
    end
    resources :moderation_notifications, path: '/notifications', only: [:create]
    resources :reviews, only: [:index, :create]
    resources :users, only: [:update]
    resources :teams, only: [:update]
    resources :events, only: [:create]
  end

  namespace :admin do
    resources :feature_settings, only: [:index, :update]
    resources :directory_segments, only: [:new, :create, :edit, :update]
    resources :organizations, only: [:new, :create]
    resources :locations, only: [:index, :show] do
      post :fetch, on: :member

      get :pending, on: :collection
      get :rejected, on: :collection
      get :moderate, on: :collection
    end
    resources :users do
      get :edit_merge, on: :member
      post :merge, on: :member
    end
    resources :templates, only: [:show]
    root 'admin#index'
  end

  resources :users, :path => '/people', :only => [:index, :show, :create, :update, :destroy] do
    post :remove_image, on: :member
    resources :users, controller: :students, as: :students, path: '/students', only: [:create, :destroy, :index]
    resources :events, controller: :user_events, only: [:index]
    resources :reviews, controller: :user_reviews, only: [:index]
  end

  resources :articles, only: [:index, :show] do
    put :publish, on: :member
    put :unpublish, on: :member
  end

  resource :map, only: [:show] do
    get :search, on: :collection
  end

  resource :geocoder, only: [:show]
  resource :search, only: [:show], controller: :search

  resources :moderation_notifications, path: '/notifications', only: [:index] do
    put :dismiss, on: :member
  end
  resources :locations, only: [:create, :destroy, :update, :show] do
    post :favorite, on: :member
    get :wizard, on: :collection
    get :recent, on: :collection
    get :nearby, on: :collection
    get :random, on: :collection
    get :schedule, on: :member

    post :move, on: :member
    post :unlock, on: :member
    post :close, on: :member
    post :remove_image, on: :member

    resource :status, controller: :location_statuses, only: [] do
      put :verify, on: :member
      put :reject, on: :member
      put :pending, on: :member
    end

    resources :reviews, controller: :location_reviews, only: [:create, :destroy, :index]

    resources :users, controller: :instructors, as: :instructors, path: '/instructors', only: [:create, :destroy, :index]

    resources :events, controller: :location_events, only: [:create, :index, :show, :destroy, :update] do
      post :move, on: :member
    end
  end

  resources :verifications, controller: :location_owner_verifications, as: :verifications, path: '/verifications', only: [:create] do
    get :verify, on: :member
  end

  resources :teams, :only => [:show, :index, :update, :create, :new, :destroy] do
    post :remove_image, on: :member
    resources :users, controller: :instructors, as: :instructors, path: '/instructors', only: [:create, :destroy, :index]
  end

  resources :events, :only => [:index, :create] do
    get :wizard, on: :collection
    get :upcoming, on: :collection
  end

  root 'application#homepage'
  get '/bjj-academy-directory' => 'directory_segments#index', :as => :directory_index
  get '/bjj-academy-directory/country/:country(/city/:city)' => 'directory_segments#show', :as => :directory_segment

  match '/signin' => 'sessions#new', :as => :signin, :via => [:post, :get]
  match '/auth/:provider/callback' => 'sessions#create', :via => [:post, :get]
  match '/auth/failure' => 'sessions#failure', :via => [:post, :get]
  match '/signout' => 'sessions#destroy', :as => :signout, :via => [:post, :get, :delete]

  post '/report' => 'application#report', :as => :report
  get '/meta' => 'application#meta', :as => :meta
  get '/privacy-policy' => 'application#privacy_policy', :as => :privacy_policy
  get '/people' => 'application#people'
  post '/contact' => 'application#contact', :as => :contact

  get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap
end

app/models/user.rb
require 'wikipedia'
require 'mongoid_search_ext'
require 'redis_cache'

class User
  include Mongoid::Document
  include Mongoid::Slug
  include Geocoder::Model::Mongoid
  include Mongoid::Timestamps
  include Mongoid::History::Trackable

  extend MongoidSearchExt::Search

  DEFAULT_THUMBNAIL_X = 50
  DEFAULT_THUMBNAIL_Y = 0

  #VALID_IMAGE_MATCH = /(^https:\/\/(common)?datastorage.googleapis.com\/bjjmapper\/)|(^https:\/\/upload.wikimedia.org)/

  track_history   :on => :all,
                  :modifier_field => :modifier, # adds "belongs_to :modifier" to track who made the change, default is :modifier
                  :modifier_field_inverse_of => nil, # adds an ":inverse_of" option to the "belongs_to :modifier" relation, default is not set
                  :version_field => :version,   # adds "field :version, :type => Integer" to track current version, default is :version
                  :track_create   =>  true,    # track document creation, default is false
                  :track_update   =>  true,     # track document updates, default is true
                  :track_destroy  =>  true     # track document destruction, default is false

  field :role, type: String
  field :provider, type: String
  field :uid, type: String
  field :nickname, type: String
  field :name, type: String
  slug :name, history: true do |obj|
    obj.anonymous? ? obj.ip_address.try(:to_url) : obj.name.to_url
  end

  field :preferences, default: {}.with_indifferent_access
  field :api_key, type: String
  field :email, type: String
  field :contact_email, type: String
  field :thumbnailx, type: Integer, default: DEFAULT_THUMBNAIL_X
  field :thumbnaily, type: Integer, default: DEFAULT_THUMBNAIL_Y
  field :image_tiny, type: String
  field :image_large, type: String
  field :image, type: String
  field :cover_image, type: String
  field :ip_address, type: String
  field :coordinates, type: Array
  field :last_seen_at, type: Integer
  field :description, type: String
  field :description_read_more_url, type: String
  field :description_src, type: String
  field :source, type: String

  field :oauth_token, type: String
  field :oauth_expires_at, type: Integer

  field :belt_rank, type: String
  field :stripe_rank, type: Integer
  field :birth_day, type: Integer
  field :birth_month, type: Integer
  field :birth_year, type: Integer
  field :birth_place, type: String
  field :deceased_day, type: Integer
  field :deceased_month, type: Integer
  field :deceased_year, type: Integer
  field :internal, type: Boolean
  field :female, type: Boolean

  field :flag_stub, type: Boolean, default: false
  field :flag_display_email, type: Boolean, default: false
  field :flag_display_directory, type: Boolean, default: true
  field :flag_display_reviews, type: Boolean, default: true
  field :flag_locked, type: Boolean, default: -> { self.provider.present? }

  validates :name, presence: true

  #validate :valid_image_prefix?

  geocoded_by :ip_address
  after_validation :safe_geocode

  belongs_to :lineal_parent, class_name: 'User', inverse_of: :lineal_children
  has_many :lineal_children, class_name: 'User', inverse_of: :lineal_parent
  has_many :reviews, inverse_of: :user
  has_many :owned_locations, class_name: 'Location', inverse_of: :owner

  belongs_to :redirect_to_user, class_name: 'User', inverse_of: :redirected_to_user
  has_one :redirected_to_user, class_name: 'User', inverse_of: :redirect_to_user

  has_and_belongs_to_many :teams
  has_and_belongs_to_many :locations, index: true, inverse_of: :instructors
  has_and_belongs_to_many :favorite_locations, class_name: 'Location', index: true, inverse_of: :favorited_by

  index({
      :name => 'text',
      :nickname => 'text',
      :contact_email => 'text',
      :description => 'text'
    },
    {
      :name => 'user_text_index',
      :weights => {
        :name => 20,
        :nickname => 15,
        :description => 10,
        :contact_email => 10
      }
    }
  )

  default_scope -> { where(:redirect_to_user_id => nil) }
  scope :jitsukas, -> { where(:belt_rank.in => ['blue', 'purple', 'brown', 'black']) }

  #def self.grandmasters
  #  user_ids = RollFindr::Redis.zrevrange('UserStudentCount', 0, 10)
  #  User.where(:id.in => user_ids).sort_by(&:student_count).reverse
  #end

  #def student_count
  #  RollFindr::Redis.cache(expire: 1.hour.seconds, key: ['UserStudentCount', self.id.to_s].join('-')) do
  #    RollFindr::Redis.zadd('UserStudentCount', self.lineal_children.count, self.id.to_s)
  #    self.lineal_children.count
  #  end
  #end
  #

  def preference(sym)
    preferences[sym]
  end

  def preferences
    @_preferences ||= (self.read_attribute(:preferences) || {}).with_indifferent_access
  end

  def set_preference!(sym, val)
    preferences[sym] = val
    self.update_attribute(:preferences, preferences)
  end

  def set_preferences!(prefs)
    preferences.merge!(prefs)
    self.update_attribute(:preferences, preferences)
  end

  def populate_from_wikipedia!
    page = Wikipedia.find(name)
    if page.content.present?
      self.image = page.image_urls.detect { |x| !x.end_with?('svg') } unless self.image.present?
      self.description_src = :wikipedia
      self.description = page.summary.gsub(/\n/, "\r\n\r\n")
      self.description_read_more_url = page.fullurl
      self.save
    end
  end

  def can_destroy? object
    if object.respond_to?(:destroyable_by?)
      object.destroyable_by? self
    else
      object.editable_by? self
    end
  end

  def can_edit? object
    object.editable_by? self
  end

  def editable_by? user
    return true if user.super_user?
    return false if user.anonymous?

    !self.flag_locked? || user.id.eql?(self.id)
  end

  def lat
    self.coordinates.try(:[], 1)
  end

  def lng
    self.coordinates.try(:[], 0)
  end

  def jitsuka?
    self.belt_rank.present?
  end

  def self.rank_sort_key(belt_rank, stripe_rank)
    belt = belt_rank.try(:downcase) || 'white'
    stripe = stripe_rank || 0
    key = {'white' => 0, 'blue' => 100, 'purple' => 200, 'brown' => 300, 'black' => 400}[belt] + stripe
    return -key
  end

  def self.anonymous(ip_address)
    User.where(role: Role::ANONYMOUS, ip_address: ip_address).first_or_create(provider: 'anonymous', role: Role::ANONYMOUS, name: "Anonymous #{ip_address}", last_seen_at: Time.now)
  end

  def self.from_omniauth(auth, ip_address)
    email = auth.try(:[], 'info').try(:[], 'email')
    User.where(provider: auth['provider'], uid: auth['uid'])
        .first_or_initialize(
          name: auth.try(:[], 'info').try(:[], 'name'),
          email: email,
          contact_email: email,
          ip_address: ip_address,
          oauth_token: auth.try(:credentials).try(:token),
          oauth_expires_at: Time.at(auth.try(:credentials).try(:expires_at) || 0),
          last_seen_at: Time.now
        )
  end

  def anonymous?
    self.role.try(:to_s).try(:eql?, 'anonymous')
  end

  def super_user?
    self.role.try(:to_s).try(:eql?, 'super_user')
  end

  def schedule
    @_schedule ||= UserSchedule.new(self.id)
  end

  def full_lineage
    # TODO: Is this expensive? Is caching enough?
    lineage = []
    u = self.lineal_parent
    while u.present?
      lineage << u
      u = u.lineal_parent
      break if lineage.count > 10
    end

    lineage
  end

  def birthdate
    return nil unless birth_year.present? && birth_month.present? && birth_day.present?
    Date.new(birth_year, birth_month, birth_day) rescue nil
  end

  def deceased_date
    return nil unless deceased_year.present?
    Date.new(deceased_year, deceased_month, deceased_day) rescue nil
  end

  def deceased?
    return deceased_date.present?
  end

  def age_in_years
    d = Time.now
    a = d.year - birth_year
    a = a - 1 if (
         birth_month >  d.month or
        (birth_month >= d.month and birth_day > d.day)
    )
    a
  end

  def to_param
    slug || id
  end

  def as_json(args = {})
    raise StandardError, "Use a JBuilder template"
  end

  private

  def safe_geocode
    begin
      geocode
    rescue StandardError => e
      Rails.logger.error(e)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user

  def show
  end

  def edit_merge
  end

  def merge
    tracker.track('mergeUser',
      src_id: @user.to_param,
      dst_id: current_user.to_param
    )

    merge_params = {
      :location_ids => current_user.location_ids.concat(@user.location_ids),
      :team_ids => current_user.team_ids.concat(@user.team_ids),
      :favorite_location_ids => current_user.favorite_location_ids.concat(@user.favorite_location_ids)
    }.merge(create_params)

    current_user.update!(merge_params)
    @user.update!({
      :redirect_to_user => current_user,
      :provider => nil,
      :location_ids => [],
      :favorite_location_ids => [],
      :team_ids => [],
      :oauth_token => nil,
      :role => 'stub'
    })

    redirect_to user_path(current_user, merge: 1)
  end

  private

  def create_params
    p = params.require(:user).permit(
      :name,
      :email,
      :image,
      :image_tiny,
      :image_large,
      :belt_rank,
      :stripe_rank,
      :birth_day,
      :birth_month,
      :birth_year,
      :lineal_parent_id,
      :birth_place,
      :description,
      :female,
      :flag_display_email,
      :flag_display_directory,
      :flag_display_reviews,
      :flag_locked)

    p[:modifier] = current_user if signed_in?
    p
  end

  def set_user
    @user = User.unscoped.find(params[:id])
    render status: :not_found and return unless @user.present?
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  include Api::UserCreateParams
  
  before_action :set_user, only: [:update]
  helper_method :user

  def update
    @user.update!(api_user_create_params)

    respond_to do |format|
      format.json { render(partial: 'users/user', object: @user) }
    end
  end

  private

  def user
    @user
  end

  def set_user
    @user = User.unscoped.find(params[:id])
    head :not_found and return false unless @user.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserCreateParams 
  
  before_action :set_user, only: [:destroy, :show, :update, :remove_image]
  before_action :redirect_legacy_bsonid, only: [:destroy, :show, :update, :remove_image]
  before_action :ensure_signed_in, only: [:update, :create, :remove_image]
  before_action :check_permissions, only: [:destroy, :update, :remove_image]

  decorates_assigned :user, :users

  helper_method :created?
  helper_method :welcome?
  helper_method :own_profile?

  REVIEW_COUNT_DEFAULT = 5
  REVIEW_COUNT_MAX = 50

  def index
    @rank = params.fetch(:rank, nil)
    @query = params.fetch(:query, nil)
    @scope = @rank.present? ? User.where(belt_rank: @rank) : User.jitsukas

    @users = @scope
      .where(:flag_display_directory => true)
      .where(:role.ne => 'anonymous')
      .asc(:name)

    if @query.present?
      @users = @users.search(@query)
    end

    tracker.track('showUsersIndex')

    respond_to do |format|
      format.json { render json: @users.collect{ |o| { id: o.id.to_s, name: [o.name, o.nickname].compact.join(', ') } } }
    end
  end

  def show
    tracker.track('showUser',
      id: @user.to_param
    )

    respond_to do |format|
      format.json do
        if @user.redirect_to_user.present?
          @user = @user.redirect_to_user
        end
        render partial: 'users/user'
      end
      format.html do
        if @user.redirect_to_user.present?
          redirect_to user_path(@user.redirect_to_user)
        else
          render
        end
      end
    end
  end

  def create
    @user = User.create(user_create_params)

    tracker.track('createUser',
      user: @user.attributes.as_json({}),
      valid: @user.valid?
    )

    respond_to do |format|
      format.json { render partial: 'users/user' }
      format.html { redirect_to user_path(@user, edit: 1, create: 1) }
    end
  end

  def update
    tracker.track('updateUser',
      id: @user.to_param,
      user: @user.attributes.as_json({}),
      updates: user_create_params
    )

    @user.update!(user_create_params)

    respond_to do |format|
      format.json { render partial: 'users/user' }
      format.html { redirect_to user_path(@user, edit: 0) }
    end
  end

  def destroy
    tracker.track('deleteUser',
      id: @user.to_param,
      user: @user.attributes.as_json({})
    )

    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { render partial: 'users/user' }
    end
  end

  def remove_image
    tracker.track('removeUserImage',
      id: @user.to_param,
      image: @user.image
    )

    @user.update!({
      :image => nil,
      :image_large => nil,
      :image_tiny => nil
    })

    respond_to do |format|
      format.json { render partial: 'users/user' }
    end
  end

  private

  def check_permissions
    head :forbidden and return false unless current_user.can_edit?(@user)
  end

  def welcome?
    params.fetch(:welcome, 0).to_i.eql?(1)
  end

  def created?
    return params.fetch(:create, 0).to_i.eql?(1)
  end

  def redirect_legacy_bsonid
    redirect_legacy_bsonid_for(@user, params[:id])
  end

  def set_user
    @user = User.unscoped.find(params[:id])
    head :not_found and return false unless @user.present?
  end

  def own_profile?
    return false unless defined?(@user)

    return @user.id.eql?(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def upload_image_user_path(user)
    "/service/avatar/upload/users/#{user.id}/async"
  end
end

app/views/admin/users/edit_merge.html.haml
.container.show-user
  .row
    .col-md-12
      %h1 Merge Profiles
  .row
    .col-md-12
      .alert.alert-warning.buffer-top-sm{:role => 'alert'}
        %button.close{"data-dismiss" => "alert", :type => "button"} 
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %strong After completing this action, the source profile (#{user.name}) will no longer be available. 
        %span All content created by or linked to the source profile (#{user.name}) will be merged into the destination (#{current_user.name}) profile. Please proceed with caution. 


  = form_for(current_user, method: :post, url: merge_user_path(user)) do |f|
    .row
      .col-xs-10.col-md-4.col-md-offset-1.editable
        %h3 
          Source Profile
          %button.btn.btn-primary.btn-sm{:type => 'button', 'data-copy-all' => true} 
            %span.fa.fa-copy
            Copy all fields
        .text-center.center-block.display-field.avatar.buffer-top-sm.clear{:style => "width: 100px; height: 100px; background: url('#{user.image}') top center no-repeat"}
        .display-field= render partial: 'users/table', locals: { :f => f, :user => user, :show_biography => true }
      .col-xs-2.col-md-1
        %table.table.table-user-information
          %tbody
            %tr
              %td.text-muted.text-right{:style => 'height: 130px'}
                %button.btn.btn-primary.btn-sm{:type => 'button', :style => 'visibility: hidden'} &nbsp;
                %button.btn.btn-default.btn-sm{'data-copy-image' => true, :title => 'Copy Image', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right.h1
                - if user.name.present?
                  %button.btn.btn-default.btn-sm{'data-copy-name' => true, :title => 'Copy Name', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right
                - if user.belt_rank.present?
                  %button.btn.btn-default.btn-sm{'data-copy-rank' => true, :title => 'Copy Rank', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right
                - if user.birthdate.present?
                  %button.btn.btn-default.btn-sm{'data-copy-birthdate' => true, :title => 'Copy Birthdate', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right
                - if user.birth_place.present?
                  %button.btn.btn-default.btn-sm{'data-copy-birthplace' => true, :title => 'Copy Birthplace', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right
                - if user.lineal_parent.present?
                  %button.btn.btn-default.btn-sm{'data-copy-lineage' => true, :title => 'Copy Lineage', :type => :button} &raquo;
            %tr
              %td.text-muted.text-right
            %tr
              %td.text-muted.text-right
                - if user.description?
                  %button.btn.btn-default.btn-sm{'data-copy-description' => true, :title => 'Copy Description', :type => :button} &raquo;
      .col-xs-10.col-md-5.editable.edit-mode
        .edit-field
          %h3 
            Destination Profile
            %button.btn.btn-primary.btn-sm{:type => 'button', 'data-reset-all' => true} 
              %span.fa.fa-repeat
              Use all existing fields
        .text-center.center-block.edit-field.avatar.buffer-top-sm.clear{:style => "height: 100px; width: 100px; background: url('#{current_user.image}') top center no-repeat"}
        .edit-field= f.hidden_field :image
        .edit-field= f.hidden_field :image_large
        .edit-field= f.hidden_field :image_tiny
        .edit-field= render partial: 'users/edit_table', locals: { :f => f, :user => current_user, :show_biography => true }

    .row
      .col-md-6
      .col-md-6
        .text-center.center-block
          %button.btn.btn-lg.btn-primary{:type => :submit}
            %span.fa.fa-code-fork.fa-rotate-180
            Merge Profiles

= content_for(:scripts) do
  :coffeescript
    $(document).ready ->
      sourceUser = new RollFindr.Models.User(#{render_json(user)})
      destUser = new RollFindr.Models.User(#{render_json(current_user)})
      mergeView = new RollFindr.Views.UserMergeView({ src: sourceUser, dest: destUser })

app/views/admin/users/show.html.haml
.container
  %h3 Model
  %pre.small= JSON.pretty_generate(@user.as_json({}))
  %h3= pluralize(@user.history_tracks.count, "Changes")
  %table.table.table-striped
    %tr
      %th Action
      %th Modified
      %th Original
      %th Version
      %th Modifier
      %th Time

    - @user.history_tracks.sort_by { |o| -o.version }.each do |history|
      %tr
        %td= history.action
        %td
          %pre= JSON.pretty_generate(history.modified)
        %td
          %pre= JSON.pretty_generate(history.original)
        %td= history.version
        %td= history.modifier.present? ? link_to(history.modifier.name, history.modifier) : '(none)'
        %td= time_ago_in_words(history.created_at)